updated it but have error (see comment)
ypeError("Parameter 2 is a instance of the SpriteList instead of a required Sprite. See if you meant to "
TypeError: Parameter 2 is a instance of the SpriteList instead of a required Sprite.